import { City } from "../types/database_types";

export const FakeCityChicago: City = {
    id: "123",
    name: "Chicago",
    state_id: "123",
    average_rent: 1,
    total_population: 8,
    caucasian_population: 1,
    black_population: 1,
    native_american_population: 1,
    asian_population: 1,
    pacific_islander_population: 1,
    hispanic_population: 1,
    population_under_25: 1,
    population_25_to_29: 1,
    population_30_to_34: 1,
    population_35_to_44: 1,
    population_45_to_54: 1,
    population_55_to_64: 1,
    population_65_to_74: 1,
    population_75_and_older: 1,
    male_population: 1,
    female_population: 1,
    avg_temp_jan: 20.6,
    avg_temp_feb: 27.4,
    avg_temp_march: 40.7,
    avg_temp_april: 47,
    avg_temp_may: 63.7,
    avg_temp_june: 72.2,
    avg_temp_july: 75.3,
    avg_temp_aug: 74.4,
    avg_temp_sept: 67.4,
    avg_temp_oct: 54,
    avg_temp_nov: 43.4,
    avg_temp_dec: 29.1,
    average_groceries_cost: 7.34,
    average_utility_cost: 1,
    average_electricity_cost: 4,
    average_gas_cost: 1,
    average_trash_cost: 2,
    average_water_cost: 7,
    state_abortion_laws: "Fully legal",
    state_cannabis_legality: "Medicinal use only",
    crime_rate_per_1000: 2345.90,
    state_school_score: 10
}

export const FakeCityNYC: City = {
    id: "123",
    name: "Chicago",
    state_id: "123",
    average_rent: 1,
    total_population: 108,
    caucasian_population: 1,
    black_population: 1,
    native_american_population: 1,
    asian_population: 1,
    pacific_islander_population: 1,
    hispanic_population: 1,
    population_under_25: 100,
    population_25_to_29: 1,
    population_30_to_34: 1,
    population_35_to_44: 1,
    population_45_to_54: 1,
    population_55_to_64: 1,
    population_65_to_74: 1,
    population_75_and_older: 1,
    male_population: 1,
    female_population: 1,
    avg_temp_jan: 80,
    avg_temp_feb: 80,
    avg_temp_march: 80,
    avg_temp_april: 80,
    avg_temp_may: 80,
    avg_temp_june: 80,
    avg_temp_july: 80,
    avg_temp_aug: 80,
    avg_temp_sept: 80,
    avg_temp_oct: 80,
    avg_temp_nov: 80,
    avg_temp_dec: 80,
    average_groceries_cost: 3,
    average_utility_cost: 1,
    average_electricity_cost: 4,
    average_gas_cost: 1,
    average_trash_cost: 2,
    average_water_cost: 7,
    state_abortion_laws: "Fully legal",
    state_cannabis_legality: "Medicinal use only",
    crime_rate_per_1000: 2345.90,
    state_school_score: 10
}