import { City } from "../types/database_types";

export const FakeCityChicago: City = {
    id: "123",
    name: "Chicago",
    state_id: "123",
    average_rent: 1,
    total_population: 8,
    caucasian_population: 1,
    black_population: 1,
    native_american_population: 1,
    asian_population: 1,
    pacific_islander_population: 1,
    hispanic_population: 1,
    population_under_25: 1,
    population_25_to_29: 1,
    population_30_to_34: 1,
    population_35_to_44: 1,
    population_45_to_54: 1,
    population_55_to_64: 1,
    population_65_to_74: 1,
    population_75_and_older: 1,
    male_population: 1,
    female_population: 1,
    avg_temp_jan: 1,
    avg_temp_feb: 1,
    avg_temp_march: 1,
    avg_temp_april: 1,
    avg_temp_may: 1,
    avg_temp_june: 1,
    avg_temp_july: 1,
    avg_temp_aug: 1,
    avg_temp_sept: 1,
    avg_temp_oct: 1,
    avg_temp_nov: 1,
    avg_temp_dec: 1,
    average_groceries_cost: 1
}

export const FakeCityNYC: City = {
    id: "123",
    name: "Chicago",
    state_id: "123",
    average_rent: 1,
    total_population: 108,
    caucasian_population: 1,
    black_population: 1,
    native_american_population: 1,
    asian_population: 1,
    pacific_islander_population: 1,
    hispanic_population: 1,
    population_under_25: 100,
    population_25_to_29: 1,
    population_30_to_34: 1,
    population_35_to_44: 1,
    population_45_to_54: 1,
    population_55_to_64: 1,
    population_65_to_74: 1,
    population_75_and_older: 1,
    male_population: 1,
    female_population: 1,
    avg_temp_jan: 1,
    avg_temp_feb: 1,
    avg_temp_march: 1,
    avg_temp_april: 1,
    avg_temp_may: 1,
    avg_temp_june: 1,
    avg_temp_july: 1,
    avg_temp_aug: 1,
    avg_temp_sept: 1,
    avg_temp_oct: 1,
    avg_temp_nov: 1,
    avg_temp_dec: 1,
    average_groceries_cost: 1
}